name: adonis-os-blog-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-version: 5.0

            - name: Setup MongoDB
              run: make setup-mongo

            - name: Install Dependencies
              run: make install

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              env:
                  MONGO_DB: testBlog
                  MONGO_COLLECTION_POST: post
                  MONGO_COLLECTION_AUTH_RECORD: authRecord
                  MONGO_USER: runner
                  MONGO_PASSWORD: mongodb
                  MONGO_ADDRESS: localhost
                  MONGO_PORT: 27017
                  NODE_ENV: test
              run: |
                  make test
                  rm -rf __tests__

            - name: Run Build
              env:
                  NEXT_PUBLIC_FIREBASE_API_KEY: key
                  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: domain
                  NEXT_PUBLIC_FIREBASE_PROJECT_ID: id
                  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: bucket
                  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: sender
                  NEXT_PUBLIC_FIREBASE_APP_ID: id
                  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: id
              run: make build
